### ISSUE TITLE
Issue with Memory Implementation in ReWOO Agent

### ISSUE THREAD

**Issue by frankliu098** [Gentopia-AI/Gentopia#61]
I'm trying to implement both Short and Long term Memory with the ReWOO Agent. Below is the configuration I used in my ReWOO Agent YAML file. However, when I conduct multiple conversations with the agent through Gentopia's interface, the LLM doesn't seem to retain memory as expected.

```yaml
memory:
  memory_type: chroma
  conversation_threshold: 2      # first-level memory
  reasoning_threshold: 2         # second-level memory
  params:
    index: main
    top_k: 2
```

Can anyone confirm if the Short and Long term Memory has been correctly implemented for the ReWOO Agent, or if there's something I'm missing in my configuration?
